import serums from "../assets/serums.jpg";
import lotions from "../assets/lotions.jpg";
import shampoos from "../assets/shampoos.jpg";
import soaps from "../assets/soaps.jpeg";
import creams from "../assets/creams.jpg";

export const productsData = {
  Serums: [
    {
      productId: 1,
      category: "Serums",
      image: "https://via.placeholder.com/300x300?text=Glow+Boost",
      name: "Glow Boost Vitamin C Serum",
      rating: "A",
      description: "Brightening serum with 20% vitamin C, hyaluronic acid, and ferulic acid for radiant skin.",
      rating_explanation: "Highly effective for brightening and reducing dark spots with minimal irritation.",
      category_notes: "Serums are concentrated treatments targeting specific concerns like aging, hydration, or pigmentation.",
    },
    {
      productId: 2,
      category: "Serums",
      image: "https://via.placeholder.com/300x300?text=Hyaluronic",
      name: "Hyaluronic Hydration Serum",
      rating: "A",
      description: "Ultra-lightweight serum with 3 molecular weights of hyaluronic acid for deep hydration.",
      rating_explanation: "Instant plumping effect with long-lasting moisture retention.",
      category_notes: "Hydration serums often contain humectants like hyaluronic acid or glycerin.",
    },
    {
      productId: 3,
      category: "Serums",
      image: "https://via.placeholder.com/300x300?text=Retinol",
      name: "Retinol Renewal Night Serum",
      rating: "B",
      description: "Encapsulated retinol serum (0.5%) with soothing niacinamide for anti-aging benefits.",
      rating_explanation: "Effective but may cause mild peeling during adjustment period.",
      category_notes: "Retinol serums should be introduced gradually to avoid irritation.",
    },
    {
      productId: 4,
      category: "Serums",
      image: "https://via.placeholder.com/300x300?text=Green+Tea",
      name: "Green Tea Antioxidant Serum",
      rating: "B",
      description: "Antioxidant-rich serum with green tea extract, vitamin E, and panthenol for stressed skin.",
      rating_explanation: "Great for calming redness but lighter texture may not suit very dry skin.",
      category_notes: "Antioxidant serums help protect against environmental damage.",
    },
    {
      productId: 5,
      category: "Serums",
      image: "https://via.placeholder.com/300x300?text=Niacinamide",
      name: "Pore Refining Niacinamide Serum",
      rating: "A",
      description: "10% niacinamide serum with zinc PCA to regulate sebum and minimize pores.",
      rating_explanation: "Shows visible results in pore appearance within 4 weeks.",
      category_notes: "Niacinamide serums often target oil control and barrier repair.",
    },
    {
      productId: 0,
      category: "Serums",
      image: "https://via.placeholder.com/300x300?text=CBD",
      name: "CBD Calming Serum",
      rating: "C",
      description: "Full-spectrum CBD serum with chamomile and oat extract for sensitive skin.",
      rating_explanation: "Soothing but limited evidence for CBD's topical benefits at this concentration.",
      category_notes: "Specialty serums may contain novel ingredients with varying research support.",
    },
  ],
  Lotions: [
    {
      productId: 1,
      category: "Lotions",
      image: "https://via.placeholder.com/300x300?text=Daily+Moisture",
      name: "Daily Moisture Light Lotion",
      rating: "B",
      description: "Oil-free moisturizing lotion with squalane and ceramides for normal to oily skin.",
      rating_explanation: "Reliable basic moisturizer but lacks advanced ingredients.",
      category_notes: "Lotions are lighter than creams, ideal for daytime or warmer climates.",
    },
    {
      productId: 2,
      category: "Lotions",
      image: "https://via.placeholder.com/300x300?text=Shea+Butter",
      name: "Shea Butter Body Lotion",
      rating: "A",
      description: "Rich emollient lotion with 10% shea butter and coconut oil for dry skin.",
      rating_explanation: "Highly effective for very dry skin without greasy residue.",
      category_notes: "Body lotions focus on larger surface area coverage with simpler formulations.",
    },
    {
      productId: 3,
      category: "Lotions",
      image: "https://via.placeholder.com/300x300?text=SPF+30",
      name: "SPF 30 Facial Lotion",
      rating: "B",
      description: "Mineral sunscreen lotion with zinc oxide and antioxidant blend.",
      rating_explanation: "Good UV protection but can leave slight white cast.",
      category_notes: "Sunscreen lotions combine moisturization with UV protection.",
    },
    {
      productId: 4,
      category: "Lotions",
      image: "https://via.placeholder.com/300x300?text=After+Sun",
      name: "After Sun Cooling Lotion",
      rating: "A",
      description: "Aloe vera and menthol infused lotion for post-sun exposure relief.",
      rating_explanation: "Immediate cooling sensation with effective hydration.",
      category_notes: "Specialty lotions address specific temporary skin conditions.",
    },
    {
      productId: 0,
      category: "Lotions",
      image: "https://via.placeholder.com/300x300?text=Fragrance+Free",
      name: "Fragrance-Free Sensitive Skin Lotion",
      rating: "A",
      description: "Hypoallergenic lotion with colloidal oatmeal and allantoin.",
      rating_explanation: "Clinically tested for eczema-prone skin with excellent tolerance.",
      category_notes: "Sensitive skin lotions avoid common irritants like fragrance or dyes.",
    },
  ],
  Shampoos: [
    {
      productId: 1,
      category: "Shampoos",
      image: "https://via.placeholder.com/300x300?text=Volume+Boost",
      name: "Volume Boost Shampoo",
      rating: "B",
      description: "Sulfate-free shampoo with biotin and rice proteins for fine hair.",
      rating_explanation: "Provides good lift but may require clarifying wash occasionally.",
      category_notes: "Volumizing shampoos often contain proteins to thicken hair strands.",
    },
    {
      productId: 2,
      category: "Shampoos",
      image: "https://via.placeholder.com/300x300?text=Moisture+Repair",
      name: "Moisture Repair Shampoo",
      rating: "A",
      description: "Creamy shampoo with shea butter and argan oil for dry, damaged hair.",
      rating_explanation: "Effectively moisturizes without weighing hair down.",
      category_notes: "Hydrating shampoos typically contain oils and humectants.",
    },
    {
      productId: 3,
      category: "Shampoos",
      image: "https://via.placeholder.com/300x300?text=Scalp+Balance",
      name: "Scalp Balance Shampoo",
      rating: "A",
      description: "Medicated shampoo with 1% pyrithione zinc for dandruff control.",
      rating_explanation: "Clinically proven to reduce flaking and itching.",
      category_notes: "Anti-dandruff shampoos contain active ingredients to treat scalp conditions.",
    },
    {
      productId: 4,
      category: "Shampoos",
      image: "https://via.placeholder.com/300x300?text=Charcoal",
      name: "Purifying Charcoal Shampoo",
      rating: "B",
      description: "Detox shampoo with activated charcoal and tea tree oil for buildup removal.",
      rating_explanation: "Effective cleanser but may be drying for some hair types.",
      category_notes: "Clarifying shampoos deeply cleanse but shouldn't be used daily.",
    },
    {
      productId: 5,
      category: "Shampoos",
      image: "https://via.placeholder.com/300x300?text=Color+Protect",
      name: "Color Protect Shampoo",
      rating: "B",
      description: "Sulfate-free formula with UV filters to maintain hair color vibrancy.",
      rating_explanation: "Gentle cleansing but color protection benefits are subtle.",
      category_notes: "Color-safe shampoos avoid harsh detergents that strip dye.",
    },
    {
      productId: 0,
      category: "Shampoos",
      image: "https://via.placeholder.com/300x300?text=Baby+Shampoo",
      name: "Baby Gentle Wash Shampoo",
      rating: "A",
      description: "Tear-free formula with chamomile and provitamin B5.",
      rating_explanation: "Extremely mild with pleasant natural fragrance.",
      category_notes: "Baby shampoos have extra mild formulations for delicate scalps.",
    },
  ],
  Soaps: [
    {
      productId: 1,
      category: "Soaps",
      image: "https://via.placeholder.com/300x300?text=Castile+Soap",
      name: "Olive Oil Castile Soap",
      rating: "A",
      description: "Plant-based soap made with saponified olive oil, gentle for sensitive skin.",
      rating_explanation: "Non-drying formula suitable for face and body.",
      category_notes: "Castile soaps are vegetable oil-based rather than animal fat-based.",
    },
    {
      productId: 2,
      category: "Soaps",
      image: "https://via.placeholder.com/300x300?text=Antibacterial",
      name: "Antibacterial Bar Soap",
      rating: "C",
      description: "Deodorizing soap with 1% triclosan for germ protection.",
      rating_explanation: "Effective but may disrupt skin microbiome with prolonged use.",
      category_notes: "Antibacterial soaps are controversial for routine home use.",
    },
    {
      productId: 3,
      category: "Soaps",
      image: "https://via.placeholder.com/300x300?text=Charcoal+Soap",
      name: "Exfoliating Charcoal Soap",
      rating: "B",
      description: "Activated charcoal soap with ground walnut shells for physical exfoliation.",
      rating_explanation: "Good for oily skin but abrasive for sensitive types.",
      category_notes: "Exfoliating soaps may contain physical or chemical exfoliants.",
    },
    {
      productId: 4,
      category: "Soaps",
      image: "https://via.placeholder.com/300x300?text=Goat+Milk",
      name: "Goat Milk Moisturizing Soap",
      rating: "A",
      description: "Handcrafted soap with goat milk, honey, and oatmeal for dry skin.",
      rating_explanation: "Exceptionally creamy lather that doesn't strip skin.",
      category_notes: "Milk soaps contain natural fats that boost moisturization.",
    },
    {
      productId: 5,
      category: "Soaps",
      image: "https://via.placeholder.com/300x300?text=Glycerin+Soap",
      name: "Transparent Glycerin Soap",
      rating: "B",
      description: "Clear soap with vegetable glycerin and essential oil blends.",
      rating_explanation: "Gentle cleanser but may leave slight residue.",
      category_notes: "Glycerin soaps attract moisture to the skin during cleansing.",
    },
    {
      productId: 0,
      category: "Soaps",
      image: "https://via.placeholder.com/300x300?text=Ayurvedic",
      name: "Neem & Turmeric Ayurvedic Soap",
      rating: "B",
      description: "Traditional formula with antibacterial neem and brightening turmeric.",
      rating_explanation: "Distinct medicinal aroma but beneficial for problem skin.",
      category_notes: "Ayurvedic soaps incorporate traditional Indian medicinal herbs.",
    },
  ],
  Creams: [
    {
      productId: 1,
      category: "Creams",
      image: "https://via.placeholder.com/300x300?text=Night+Cream",
      name: "Intensive Repair Night Cream",
      rating: "A",
      description: "Rich cream with peptides, ceramides, and 5% urea for overnight recovery.",
      rating_explanation: "Significantly improves skin texture and hydration by morning.",
      category_notes: "Night creams are typically richer than day creams with reparative ingredients.",
    },
    {
      productId: 2,
      category: "Creams",
      image: "https://via.placeholder.com/300x300?text=BB+Cream",
      name: "BB Cream with SPF 40",
      rating: "B",
      description: "Tinted moisturizing cream with mineral sunscreen and light coverage.",
      rating_explanation: "Convenient 3-in-1 product but limited shade range.",
      category_notes: "BB creams combine skincare, sun protection, and light makeup.",
    },
    {
      productId: 3,
      category: "Creams",
      image: "https://via.placeholder.com/300x300?text=Arnica",
      name: "Arnica Relief Cream",
      rating: "B",
      description: "Muscle soothing cream with arnica montana and menthol for soreness.",
      rating_explanation: "Provides temporary relief but effects are short-lived.",
      category_notes: "Medicated creams target specific physical discomforts.",
    },
    {
      productId: 4,
      category: "Creams",
      image: "https://via.placeholder.com/300x300?text=Collagen",
      name: "Collagen Boosting Face Cream",
      rating: "C",
      description: "Anti-aging cream with retinol alternative and vitamin C derivatives.",
      rating_explanation: "Pleasant texture but collagen stimulation claims are unverified.",
      category_notes: "Many anti-aging creams make structural protein claims that are difficult to substantiate.",
    },
    {
      productId: 5,
      category: "Creams",
      image: "https://via.placeholder.com/300x300?text=Eczema",
      name: "Eczema Therapy Cream",
      rating: "A",
      description: "Steroid-free cream with colloidal oatmeal and ceramide complex.",
      rating_explanation: "Clinically shown to reduce itching and flare-ups.",
      category_notes: "Therapeutic creams for skin conditions often undergo medical testing.",
    },
    {
      productId: 6,
      category: "Creams",
      image: "https://via.placeholder.com/300x300?text=Brightening",
      name: "Whitening Brightening Cream",
      rating: "B",
      description: "Dark spot corrector with niacinamide, licorice root, and alpha-arbutin.",
      rating_explanation: "Gradual brightening effect over 8-12 weeks of consistent use.",
      category_notes: "Skin brightening creams inhibit melanin production through various mechanisms.",
    },
    {
      productId: 0,
      category: "Creams",
      image: "https://via.placeholder.com/300x300?text=Cold+Cream",
      name: "Cold Cream Cleanser",
      rating: "A",
      description: "Traditional emulsion of oils and waxes for makeup removal.",
      rating_explanation: "Exceptionally thorough yet gentle cleansing method.",
      category_notes: "Cold creams follow ancient formulations still effective today.",
    },
  ],
};

export const categories = [
  {
    name: "Serums",
    icon: serums,
  },
  {
    name: "Lotions",
    icon: lotions,
  },
  {
    name: "Shampoos",
    icon: shampoos,
  },
  {
    name: "Soaps",
    icon: soaps,
  },
  {
    name: "Creams",
    icon: creams,
  },
];
